/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nearbyearthquakes;

import nearbyearthquakes.domain.Coordinates;
import nearbyearthquakes.domain.Earthquake;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.Assert.assertEquals;

public class AppTest {

    /**
     * Test of the predicate distinctByKey for the longitude latitude uniqueness
     */
    @Test
    public void testUniquenessFilter() {
        List<Earthquake> earthquakes = new ArrayList<>();
        Earthquake e1 = new Earthquake("e1", 200, 10.2, 12.2);
        Earthquake e2 = new Earthquake("e2", 400, 10.2, 12.2);
        Earthquake e3 = new Earthquake("e3", 300, 11.2, 13.2);
        Earthquake e4 = new Earthquake("e4", 300, 14.2, 15.2);
        Earthquake e5 = new Earthquake("e5", 300, 14.2, 15.2);
        Earthquake e6 = new Earthquake("e6", 300, 14.2, 16.2);

        earthquakes.add(e1);
        earthquakes.add(e2);
        earthquakes.add(e3);
        earthquakes.add(e4);
        earthquakes.add(e5);
        earthquakes.add(e6);
        List<Earthquake> filteredEarthquakes = earthquakes.stream()
                .filter(App.distinctByKey((Coordinates::new)))
                .collect(Collectors.toList());

        assertEquals(4, filteredEarthquakes.size());

    }


}
